# Generated by Django 3.2.4 on 2021-06-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_like'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripdetail', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripdetail', to='post.post'),
        ),
    ]
