# Generated by Django 3.2.4 on 2021-06-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20210617_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetail',
            old_name='cart',
            new_name='trip',
        ),
    ]
