# Generated by Django 3.2.4 on 2021-06-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_rename_cart_tripdetail_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
